import { CMByHostnameAPIData, InopsDataType } from "~/types";

export const INOPS_DEFAULT_DATA: InopsDataType = {
  cabinet: "",
  cage: "",
  created_time: undefined,
  device_id: undefined,
  environment: "",
  fabric: "",
  fabric_group: "",
  location: "",
  manufacturer: "",
  model: "",
  multiproducts: [],
  ru: undefined,
  services: [],
  site: "",
  state: "",
  template_group: "",
  template_name: "",
  warranty_expiration: undefined,
  warranty_start: undefined,
};

const DEFAULT_FAULT_DATA = {
  check_id: "",
  component: "",
  created: "",
  created_by: "",
  description: "",
  detection_system: "",
  fault_type: "",
  health_check_url: "",
  is_manual: true,
  jira_ticket: "",
  jira_url: "",
  updated: "",
  team: "",
};

// placeholder if faultsData is undefined
export const DEFAULT_CM_DATA: CMByHostnameAPIData = {
  actionable: "no",
  app_owners: [],
  apps: [],
  check_ids: [],
  cm_id: 0,
  cm_uuid: "",
  created: "",
  created_by: "",
  fault_types: [],
  faults: [],
  hooks_enabled: false,
  hooks_plan_id: "",
  hooks_phase_name: "",
  hooks_phase_status: "",
  hostname: "",
  inops_data: INOPS_DEFAULT_DATA,
  last_updated_by: "",
  updated: "",
  status: "",
  total_faults: 0,
  workflow_state: "",
  fault: DEFAULT_FAULT_DATA,
};
